site: samrat's thought space
url: https://samratsahoo.com
title: samrat's thought space
description: chaos written down.
twitter:
  username: samratdotjs
  card: summary
  creator: samratdotjs
author:
  twitter: samratdotjs
  name: samrat sahoo
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty
markdown: kramdown
baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship

jekyll-spaceship:
  # default enabled processors
  processors:
    - mermaid-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  brain:
    output: true
  lectures:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "brain"
    values:
      layout: "brain"
