site: samrat's thought space
url: https://samratsahoo.com
title: samrat's thought space
description: chaos written down.
twitter:
  username: samratdotjs
  card: summary
  creator: samratdotjs
author:
  twitter: samratdotjs
  name: samrat sahoo
  avatar:
  email: #youremail
  url: https://samratsahoo.com
permalink: pretty
baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spaceship

jekyll-spaceship:
  # default enabled processors
  processors:
    - mermaid-processor
    - mathjax-processor
    - table-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/

  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
        scale: 1.0
        minScale: 0.5
        mtextInheritFont: true
        merrorInheritFont: true
        mathmlSpacing: false
        skipAttributes: {}
        exFactor: 0.5
      chtml:
        scale: 1.0
        minScale: 0.5
        matchFontHeight: true
        mtextFont: 'serif'
        linebreaks:
          automatic: false
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)

collections:
  pages:
    output: true
    permalink: /:name
  research:
    output: true
    permalink: /:year/:month/:day/:slug
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  brain:
    output: true
  readings:
    output: true
    permalink: /:year/:month/:day/:slug
  lectures:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "brain"
    values:
      layout: "brain"
  - scope:
      path: ""
      type: "readings"
    values:
      layout: "reading"
